# Site settings
title: Ironhanded Layman
email: nathaniel.dean@alumni.purdue.edu
description: > # this means to ignore newlines until "baseurl:"
  The base of operations for IronhandedLayman. Projects are in the process of being uncloaked. Experimentations happen daily.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ironhandedlayman.github.io" # the base hostname & protocol for your site
github_username:  IronhandedLayman

theme: minima

# Build settings
markdown: kramdown
